Repository kubernetes-sigs/minikube-gui, pull requests merged in 2023-02, with the labels that each got.

#21 add mount button to basic view
  src/basicview.cpp
  src/basicview.h
  src/fonts.cpp
  src/operator.cpp
  src/operator.h
  src/window.cpp
Labels: approved, cncf-cla: yes, size/M

#22 Refactor mount and dashboard
  src/basicview.cpp
  src/commandrunner.cpp
  src/commandrunner.h
  src/operator.cpp
Labels: approved, cncf-cla: yes, size/M

#23 Add Mount and Stop Mount Views
  minikube.pro
  src/basicview.cpp
  src/basicview.h
  src/mount.cpp
  src/mount.h
  src/operator.cpp
  src/operator.h
Labels: approved, cncf-cla: yes, size/L

#24 Add tunnel in GUI
  src/basicview.cpp
  src/basicview.h
  src/commandrunner.cpp
  src/commandrunner.h
  src/operator.cpp
  src/operator.h
Labels: approved, cncf-cla: yes, size/M

#29 CI: Add GitHub Action build jobs
  .github/dependabot.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  scripts/windows-publish.ps1
Labels: approved, cncf-cla: yes, size/L

#31 CI: Add OS to job name
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: approved, size/XS, cncf-cla: yes

#32 CI: Setup tagging and releasing automation
  .github/workflows/bump-version.yml
  .github/workflows/tag-and-release.yml
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, size/L

#33 CI: Fix sed in GitHub Action bump-version
  .github/workflows/bump-version.yml
Labels: approved, size/XS, cncf-cla: yes

#35 CI: Cleanup building
  .github/workflows/bump-version.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/tag-and-release.yml
  .github/workflows/windows.yml
  .gitignore
  Makefile
  minikube.pro
  scripts/build-windows.cmd
  scripts/bundle-windows.ps1
  scripts/windows-publish.ps1
Labels: approved, cncf-cla: yes, size/L
