Repository kubernetes-sigs/minikube-gui, pull requests merged in 2023-01, with the labels that each got.

#3 add clang format config
  .clang-format
Labels: approved, cncf-cla: yes, size/M

#5 Create .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, size/M

#10 Add fonts and constants files
  advancedview.cpp
  basicview.cpp
  constants.h
  fonts.cpp
  fonts.h
  main.cpp
  minikube.pro
  operator.cpp
  window.cpp
Labels: approved, cncf-cla: yes, size/L

#11 Add src and resources folders
  minikube.pro
  minikube.qrc
  resources/fonts/FontAwesome.otf
  resources/images/minikube.icns
  resources/images/minikube.png
  src/advancedview.cpp
  src/advancedview.h
  src/basicview.cpp
  src/basicview.h
  src/cluster.cpp
  src/cluster.h
  src/commandrunner.cpp
  src/commandrunner.h
  src/constants.h
  src/errormessage.cpp
  src/errormessage.h
  src/fonts.cpp
  src/fonts.h
  src/hyperkit.cpp
  src/hyperkit.h
  src/logger.cpp
  src/logger.h
  src/main.cpp
  src/operator.cpp
  src/operator.h
  src/paths.cpp
  src/paths.h
  src/progresswindow.cpp
  src/progresswindow.h
  src/tray.cpp
  src/tray.h
  src/updater.cpp
  src/updater.h
  src/window.cpp
  src/window.h
Labels: approved, cncf-cla: yes, size/M

#12 fix unpause button
  src/advancedview.cpp
  src/basicview.cpp
  src/constants.h
Labels: approved, size/S, cncf-cla: yes

#16 add create Icon when there is no cluster running
  src/basicview.cpp
  src/cluster.h
  src/constants.h
  src/fonts.cpp
  src/fonts.h
Labels: approved, cncf-cla: yes, size/M
