Repository kubernetes-sigs/minikube-gui, pull requests merged in 2023-03, with the labels that each got.

#36 Fix windows opening and disappearing on start
  src/progresswindow.cpp
  src/progresswindow.h
Labels: approved, cncf-cla: yes, size/M

#37 fix crash on delete
  src/progresswindow.cpp
Labels: approved, size/XS, cncf-cla: yes

#39 Fix service and addon views locking buttons
  src/operator.cpp
Labels: approved, size/XS, cncf-cla: yes

#38 wip: initial scaffolding for settings button
  src/basicview.cpp
  src/basicview.h
  src/constants.cpp
  src/constants.h
  src/operator.cpp
  src/operator.h
Labels: approved, do-not-merge/work-in-progress, cncf-cla: yes, size/L

#40 implement automated updating on macOS
  .github/workflows/tag-and-release.yml
  Makefile
  src/updater.cpp
  src/updater.h
  src/window.cpp
Labels: approved, cncf-cla: yes, size/M

#41 Finish implementing settings
  minikube.pro
  src/basicview.cpp
  src/basicview.h
  src/errormessage.cpp
  src/operator.cpp
  src/operator.h
  src/serviceview.cpp
  src/setting.cpp
  src/setting.h
  src/settings.cpp
  src/settings.h
  src/window.cpp
  src/window.h
Labels: approved, cncf-cla: yes, size/L

#42 Use minikube binary set in settings for commands
  src/basicview.cpp
  src/basicview.h
  src/commandrunner.cpp
  src/commandrunner.h
  src/operator.cpp
  src/operator.h
  src/paths.cpp
  src/paths.h
  src/settings.cpp
  src/settings.h
  src/window.cpp
  src/window.h
Labels: approved, cncf-cla: yes, size/L

#43 Use default minikube locations if config is empty
  src/settings.cpp
Labels: approved, size/XS, cncf-cla: yes
